### ISSUE TITLE
Universal Dividend or Monetary creation tab

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/cutecoin#102]
With 0.9 version, we can't see our creation of money as in previous versions.
I propose to add a new tab named `UD`, `Universal Dividend` or `Monetary creation` containing the UD value and the date we created-it.

**Comment by Insoleet** [comment]
Where were you able to see your creation of money in previous versions ?

**Comment by M5oul** [comment]
Yep, don't you?
![cutecoin-0 8 2-money-creation](https://cloud.githubusercontent.com/assets/4758871/6949189/2ff2fd66-d8c4-11e4-82d8-a58f177402bf.png)

**Comment by Insoleet** [comment]
These are sources, an element of cutecoin protocol not displayed anymre ;)
But we will do something like the date of next UD creation yeah.

**Comment by Insoleet** [comment]
Next UD is displayed in the informations tab.
