### ISSUE TITLE
Wot display refresh problem

### ISSUE THREAD

**Issue by vtexier** [ucoin-io/cutecoin#110]
When opening cutecoin, at the first draw, I am not a member, but I am in a black thick circle.
If i click on another member. My circle become red, and if I reset the draw to me, is always red.
Then I renew my membership and a member certified me. The new certification is well updated in the wot. But when I 'm back as a member in the member list, I stay red in the Wot...

* The first draw of the account member is not red if the member status is false.
* Member status change is not updated in the Wot.

**Comment by Insoleet** [comment]
With latest network code update and nodes more stable, do you still reproduce the error ?

**Comment by vtexier** [comment]
Between the nodes, the cutecoin cache and the wot code... Difficult to see what went wrong...
I suggest it's time to write functionals tests, with users scenario and a mocked api.

**Comment by Insoleet** [comment]
Well I guess it's only a call on refresh in the wot not done when a new block is mined...

**Comment by Insoleet** [comment]
What method should be called in the method refresh_block of currency_tab class ?

**Comment by Insoleet** [comment]
Fixing it...

**Comment by vtexier** [comment]
Normaly, you should run wot_tab.draw_graph(metadata) method.
But as we dont know what to give in metadata (the current node selected in the wot), I must modify the code to save the current node and add a refresh method using it. I can do it tomorrow morning...

**Comment by Insoleet** [comment]
I did it last night, don't ! :) 

It's currently being tested (i'm waiting to be a member again...)

**Comment by Insoleet** [comment]
Fixed in https://github.com/ucoin-io/cutecoin/commit/93cf7c30edcbf31578aeda969a5a01674daf0407
