### ISSUE TITLE
Second wallet missing after cleanning cache

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/cutecoin#111]
I sent money from my main wallet to an other.
Then, I deleted the cache/user informations `~./config/cutecoin` because CuteCoin won't start.
This could happens changing client.
After charging the new cache, I only got my main wallet. I've lost the other wallet and his content.

**Comment by Insoleet** [comment]
Can you check your wallet pool size ?

**Comment by M5oul** [comment]
What do you means by "wallet pool size"?

**Comment by Insoleet** [comment]
In account > configure, on the first step.

**Comment by M5oul** [comment]
Ah, ok
My wallet pool size was one.
I put it to two. Now it's ok ;)
