### ISSUE TITLE
Transaction and fuzzy boundary of filter by date

### ISSUE THREAD

**Issue by yvgithub** [ucoin-io/cutecoin#116]
Fuzzy boundary of filter by date
Filtering with Lower bound **23-4-2015**
All transactions of 24-4-2014 are in
![transac2328](https://cloud.githubusercontent.com/assets/1395647/7376301/ddf7cd68-edac-11e4-966e-5610fe05cf07.png)

Filtering with lower bound **24-4-2015** 
Just one transaction of 24-4-2015 is in
![transac2428](https://cloud.githubusercontent.com/assets/1395647/7376305/e3ded348-edac-11e4-84d5-aafdf64a2e0b.png)

**Comment by Insoleet** [comment]
Same problem as https://github.com/ucoin-io/cutecoin/issues/115

**Comment by Insoleet** [comment]
Ok my bad, this is not the same problem as #115. But this one is fixed. :)
