### ISSUE TITLE
Modal windows are displayed as multiple windows on Gnome 3 

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/cutecoin#117]
When I open secoundary windows of CuteCoin (as transaction, add a contact, certification…), GNOME display many logos. A logo for each window.

You could see bellow, the main window with the logo and an other window without the logo.
![cutecoin-many-window](https://cloud.githubusercontent.com/assets/4758871/7378761/351041fa-edf0-11e4-95b7-aeade0679b06.png)

**Comment by Insoleet** [comment]
I think it's fixed. Could I make a build and send it to you so that you can try and check it ?

**Comment by M5oul** [comment]
Yep, I'll try it.

**Comment by Insoleet** [comment]
One logo is now displayed, but two windows are displayed despite the windows being modal.

**Comment by M5oul** [comment]
Fix with GNOME 3.16 :)
