### ISSUE TITLE
Strange look like timestamp in community members

### ISSUE THREAD

**Issue by yvgithub** [ucoin-io/cutecoin#119]
Strange look like timestamp in community members
![whatthehellisthat](https://cloud.githubusercontent.com/assets/1395647/7446642/80344d14-f1ad-11e4-8a82-0479b8d02c30.png)

**Comment by Insoleet** [comment]
Nice catch... Can you send somewhere the file : 
%APPDATA%\cutecoin\__persons__
to check its state ?

**Comment by yvgithub** [comment]
https://gist.github.com/yvgithub/93bf84e19358d2161899

**Comment by Insoleet** [comment]
Ok, it will be probably fixed with the new "Identities" tab in 1.0.0. I close this one.
