### ISSUE TITLE
Filter by date wrong order

### ISSUE THREAD

**Issue by yvgithub** [ucoin-io/cutecoin#123]
Filter by date is in good order (Jacques, to cgeek, to inso, to inso 2) here:
![filterbydateorderok0 9 2](https://cloud.githubusercontent.com/assets/1395647/7507563/96444782-f43f-11e4-9b7c-c3a244f39fdf.png)

But the reverse order is wrong:
![filterbydateordernotok0 9 2](https://cloud.githubusercontent.com/assets/1395647/7507602/2d5faa58-f440-11e4-90d2-1c859f609438.png)
It should be (to inso 2, to inso, to cgeek, Jacques)

**Comment by Insoleet** [comment]
Transactions dates are linked to blocks. Since a block can have multiple transactions but one date, I don't see why they should be ordered differently.

**Comment by yvgithub** [comment]
From the user perspective and by the principle of least astonishment, the reverse of ascending order is expected [relatively by me ;)] to be equal to the descending order.

**Comment by yvgithub** [comment]
More on order of transaction
Transaction
p Pending
c Confirm

t1 Account 1 Filter by date ascending order 1c 2p 3p 4p
t2 Account 1 Filter by date ascending order 1c 2p 3p 4c
t2 Account 2 Filter by date ascending order 1c 2c 3c 4c 

The ascending order is stable and as expected.
At the same time, transaction confirm in one account and not in the other but that's another story.  

t1 Account 1 Filter by date descending order 2p 3p 4p 1c
t2 Account 1 Filter by date descending order 4c 2p 3p 1c
t2 Account 2 Filter by date descending order 2c 3c 4c 1c

The descending order is changing and i dont know why the order is what it is.

For me
Reverse(1c 2p 3p 4p) = 4p 3p 2p 1c and not 2p 3p 4p 1c
Reverse(1c 2p 3p 4c) = 4c 3p 2p 1c and not 4c 2p 3p 1c
Reverse(1c 2c 3c 4c) = 4c 3c 2c 1c and not 2c 3c 4c 1c

I have screenshots if you wish.

**Comment by Insoleet** [comment]
Should be fixed now.
