### ISSUE TITLE
May cutecoin implement identity revokation?

### ISSUE THREAD

**Issue by c-geek** [ucoin-io/cutecoin#129]
This feature is described in the protocol here : https://github.com/ucoin-io/ucoin/blob/master/doc/Protocol.md#self-revocation

Havn't tested it again yet, dunno if it still work, but it should. :grin:

**Comment by Insoleet** [comment]
That'd be great if this could be added for 0.10.

@vtexier would you agree to work on it ? It's a simple task but it uses the whole cutecoin architecture, so it'd be great for you to get a better grasp of the code ! :)

**Comment by vtexier** [comment]
I am doing it.
But i need more infos...
If I revoke a self-certification on the server, the cutecoin account is useless and should be deleted.
So I suggest to put the button in the configure dialog, beside "delete account", and with the name : 
"revoke and delete account"

If the revocation is successful, the account is deleted.

What do you think ?

**Comment by Insoleet** [comment]
Since 0.10 it is not mandatory anymore to publish an uid. The UI will adapt if the UID was published or not.

**Comment by Insoleet** [comment]
Done.
https://github.com/ucoin-io/cutecoin/commit/35336f0c432cc3e1fef0090475d7780d9ed124a3

**Comment by M5oul** [comment]
Will it be possible to revoke an identity?

**Comment by Insoleet** [comment]
It's a uCoin feature which will come with 0.2, I think ( @c-geek  ?)

**Comment by M5oul** [comment]
Yep, https://github.com/ucoin-io/ucoin/issues/196

**Comment by Insoleet** [comment]
So, yes, it will be possible on Sakia. But not right now.

**Comment by M5oul** [comment]
Following ticket https://github.com/duniter/sakia/issues/360.
