### ISSUE TITLE
Could cutecoin display underlying uCoin impl. in Network tab?

### ISSUE THREAD

**Issue by c-geek** [ucoin-io/cutecoin#133]
As [BMA API](https://github.com/ucoin-io/ucoin/blob/master/doc/HTTP_API.md#nodesummary) describes, each nodes can give its underlying uCoin implementation + version.

See http://metab.ucoin.io/node/summary for example:

```json
{
  "ucoin": {
    "software": "ucoind",
    "version": "0.11.3"
  }
}
```

Could this information be visible in CC network tab? 

![image](https://cloud.githubusercontent.com/assets/969136/7772281/885795c4-009d-11e5-82d9-25f8f8404c51.png)

**Comment by Insoleet** [comment]
Great idea !
Let's try to do this for 0.10. But maybe you'll have to wait for 0.11 !
