### ISSUE TITLE
No refresh of CuteCoin to last currents blocks

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/cutecoin#137]
After a long time running CuteCoin, the network tab and in the left corner of CuteCoin had almost more than ten delay blocks compared to our uCoin running nodes. CuteCoin isn't refreshing and stayed blocked. I need to restart CuteCoin to get the last currents blocks.

**Comment by Insoleet** [comment]
Ok.

This is probably an exception thrown during the network traversal process.

I'd need some debug informations ( -d ) to get more data on this bug.
