### ISSUE TITLE
Preferences changes not applied immediatly

### ISSUE THREAD

**Issue by vtexier** [ucoin-io/cutecoin#139]
When changing preferences, after validating with ok, nothing happened. I have to restart to apply the changes.

**Comment by Insoleet** [comment]
For 0.10, lets just add a popup warning that a restart is needed.

**Comment by Insoleet** [comment]
https://github.com/ucoin-io/cutecoin/commit/42bf8b7727cf93f822e30a27e2f257140088a457

If you think it's enough too, we can close this issue for the moment.

**Comment by vtexier** [comment]
It seems It is not so hard to change translation at runtime, catching a language change event : 

https://wiki.qt.io/How_to_create_a_multi_language_application

But it will be for version 0.11.0.

**Comment by vtexier** [comment]
In fact it is quite hard to implement translation change in the current code, because we need to refresh UI.
Current refresh methods are creating new widgets, which is not working well.
So we need to :
* Clean up the code to handle refresh with a non destructive way.
* Override retranslateUI methods to add our own custom strings.

In the meantime, here is the implementation of a dynamic switch language capability : 

* Refactor the language translator setup in core.app in a switch_language method : 
```
    def switch_language(self):
        translator = QTranslator(self.qapp)
        logging.debug("Loading translations")
        locale = self.preferences['lang']
        QLocale.setDefault(QLocale(locale))
        if translator.load(":/i18n/{0}".format(locale)):
            if QCoreApplication.installTranslator(translator):
                logging.debug("Loaded i18n/{0}".format(locale))
        else:
            logging.debug("Couldn't load translation")
 ```

* Call the switch_language method when the preferences are changed : 
 ```
    def accept(self):
        pref = {'account': self.combo_account.currentText(),
                'lang': self.combo_language.currentText(),
                'ref': self.combo_referential.currentIndex()}
        self.app.save_preferences(pref)

        # change UI translation
        self.app.switch_language()

 ```
* Add in every widget an override of the changeEvent method : 

 ```
    def changeEvent(self, event):
        """
        Intercepte LanguageChange event to translate UI
        :param QEvent QEvent: Event
        :return:
        """
        if event.type() == QEvent.LanguageChange:
            self.retranslateUi(self)
            self.refresh()
            return super(WalletsTabWidget, self).changeEvent(event)
 ```
 
That's it.

**Comment by Insoleet** [comment]
Yeah I agree that after refactoring the network, our effort should focus on enhancing the life cycle of the Widgets.

**Comment by Insoleet** [comment]
Ok so this is working. But at the moment, I can't find a way to go back to the "source language" dynamicaly. So the dynamic switch works from en_GB to fr_FR but not fr_FR to en_GB.
