### ISSUE TITLE
bugs in cutecoin 0.10.0

### ISSUE THREAD

**Issue by galuel** [ucoin-io/cutecoin#148]
In relative view we should see 1 UD, but it appears 0,90909 which is exactly the well known 10/11 fraction... :) Probably you take last UD you divide by actual one.

It appears also that M in units divided by UD in units is not the same result in relative view neither.

Also the account in MB divided by the UD in MB don't give the same result we see in relative view...

Note : you can either

(1) Calculate the DU live
(2) Use the DU in the blockchain, but as M is added of the DU just when it is calculated by uCoin, you will have a DU more in the money. So you can calculate all relative view dividing by 1,1 DU. For instance (M/N) / (1,1*DU) will give you the correct answer 1/c DU and not the incorrect 1/c + 1 (11 for 1/c = 10).

Probably the best option is the first one. So you need to calculate the DU corresponding to a M(t)+N*DU using the full monetary mass with the general formula DU(actual) = Max(DU(t);c*[M(t)+N*DU]/N) which will be the correct DU(t+1) one, if N(t) doesn't move.

It is necessary, because with second option, you will have false calculation when DU is stable.

**Comment by galuel** [comment]
There is a 3rd option (used by cgeek in metab.ucoin.io I beleive) is to use M(t) without the DU(t) added in it, you will integrate only at next step.

You can consider last DU(t) in the blockchain, as a calculation step, that leads to change M(t) at t+1 when the next DU calculation step appears. So with 1 unit of time of delay, you solve all calculation problem, and you can use only data written in the blockchain.

It is like considering two series of numbers V(n+1) = U(n) with a 1 gap in the numerotation that don't change at all the properties of the series.

**Comment by vtexier** [comment]
![cutecoin_values_units](https://cloud.githubusercontent.com/assets/2174016/8150735/98b35952-12f5-11e5-8059-76240a7d3b36.png)
![cutecoin_values_du](https://cloud.githubusercontent.com/assets/2174016/8150736/9c55b578-12f5-11e5-9ecc-de2ad5d456a7.png)
The UD referential use the UD(t+1) calculated live. I have modified the informations page to display more accurate values.
@galuel :  can you validate the screenshots ?

**Comment by galuel** [comment]
Universal Divididend of 17 387 862 cannot be UD(t+1) as it is written, since in many cases N(t+1) will not be N(t) and UD(t+1) will be different. In this solution you only calculate an intermediate value UD(t+x) with 0<x<1 that is present value between "t" and "t+1" which is the discrete time of the blockchain.

So it is correct relatively to the present time, but it will differ of the blockchain.

And the formula you use is not correct too : UD t+1 = MAX ( UD t ; c * Mt / Nt )

I suggest you keep the UD(t) blockchain value, and you show the M(t-1) and N(t) values used to calculate the UD(t) because of the correct formula :

UD t+1 = MAX ( UD t ; c * Mt / Nt+1 )

so for UD(t), you replace "t" by "t-1" and you have : 

UD t = MAX ( UD t-1 ; c * Mt-1 / Nt )

Exactly what it is used in http://www.metab.ucoin.io/#/home

So you use Mt-1 and Nt, and you will have 100% correct values corresponding to the blockchain, without any need to explain anything more, or to change "t" par "t+x" by "present time" or any other problem difficult to explain.

I think the solution used in http://www.metab.ucoin.io/#/home should be consider as the best one.

**Comment by vtexier** [comment]
Houston, we have a problem.
Do you agree that to display UD referential values, I need to divide with UD(t+1) calculated live ?
But you say that I can't calculate the next UD(t+1) because N(t+1) might be different...
So how can I calculate relative values of wallets, without UD(t+1) ?

**Comment by galuel** [comment]
You are in a discrete time, not a continuous one. So you cannot define a value (t) as the same that (t+1), you need to clarify what is value(t) and what is value(t+1), it is absolutely not what you want.

There is no problem at all, the correct value of UD(t+1) is : 

UD t+1 = MAX ( UD t ; c * Mt / Nt+1 )

But t+1 is the future, so you have not Nt+1, so you can't calculate UD(t+1) but only a UD(t+x) where t+x is the continuous present time which is between t and t+1. It is what http://www.metab.ucoin.io/#/home has called "computed" time (study this page !).

So you only can calculate, with blockchain values (t), the near past, not the future : 

UD t = MAX ( UD t ; c * Mt-1 / Nt )

So using those values, and naming them with the correct t & t-1 indice, you will have correct values.

If you use the "computed" time value to estimate UD(computed) you will have something different from UD(t) and different of UD(t+1) because you don't know what will be Nt+1.

t = near past < UD(t+x) = UD(computed) = UD(present) < t+1 = future blockchain DU calculation time.

**Comment by vtexier** [comment]
So how can I calculate relative values of wallets/transaction, without UD(t+1) ?
UD(t or t-1 ?) in the last block is included in M of the last block, so it can not be used...
So If I can not use UD of the last block, neither the calculated UD(t+1), what UD should I use ?
I' m lost here...

**Comment by galuel** [comment]
You use UD(t) and not UD(t+1). So you use M(t-1) and N(t).

You don't integrate UD(t) into M(t) before t+1, that's the point. Make the difference between blockchain calculation of UD(t), and validation of M(t) with UD(t) inside it.

Correct relative is always M(t-1)/N(t), so you cannot know M(t)/N(t+1) never, because t+1 is always the future !

**Comment by vtexier** [comment]
Internally, the UD(t) is calculated live with M(t) and N(t) of the last block with this formula : 
UD t = MAX ( UD t-1 ; c * Mt / Nt )
UD(t-1) is the last UD already included in M(t), and saved along M(t) in the last UD block.

Knowing that, those screen-shots should display the expected values.
 
![cutecoin_units](https://cloud.githubusercontent.com/assets/2174016/8170487/3570a3a6-13b1-11e5-83ad-7d02f5718c0b.png)
![cutecoin_ud](https://cloud.githubusercontent.com/assets/2174016/8170486/356b0874-13b1-11e5-9df8-4f46d5119b35.png)

**Comment by galuel** [comment]
it depends the definition of what is M(t) and what is M(t+1), as well as UD(t) and UD(t+1). A serie of numbers like Un can be defined as well with Vn with Vn+1 = Un.

What do you call M(t) exactly ? Is it the blockchain source or a calculated one ? Does it contain DU(t) ? Then it is false, because you need M(t) to calculate DU(t), and M(t+1) = M(t) + N(t+1)*DU(t) if you use the formula you have in information tab.

Since I don't know what you take from blockchain, what is "t" and what is "t+1" I cannot control exactly if what you put on the screen is correct or incorrect.

For instance : if people look their wallet in units, all, and they sum their units, they will obtain a value. Is this value what you call "M(t)" or is it M(t)+N(t)*DU(t) ? Or is it another stuff ?

And what is "t" exactly ? Is it "t" at the time of blockchain calculation of DU(t), or is another time "t+x" ?

And so what is "N(t)" you show here ? Is it the Number of members at "t" time of DU(t) blockchain calculation, or is it N(t+x = present time) ?

What are all the values at "t" time of UD(t) blockchain calculation, and what are the values of the blockchain at the time you show information ?

**Comment by vtexier** [comment]
>
For instance : if people look their wallet in units, all, and they sum their units, they will obtain a value. Is this value what you call "M(t)" or is it M(t)+N(t)*DU(t) ? Or is it another stuff ?

Yes, M(t) is the sum of all the wallets at the current time. I take it from the last block, but it will not change until the next UD will be added.

>
And what is "t" exactly ? Is it "t" at the time of blockchain calculation of DU(t), or is another time "t+x" ?

t is now, the current time at the moment of the display.

>
And so what is "N(t)" you show here ? Is it the Number of members at "t" time of DU(t) blockchain calculation, or is it N(t+x = present time) ?

N(t) is the number of members validated in the last block of the blockchain. So at the time of the display.

>
What are all the values at "t" time of UD(t) blockchain calculation, and what are the values of the blockchain at the time you show information ?

At the time "t" of the display, I am sure of the M value and the N value because for me they are valid in the last block.
Based on this values, I calculate the UD(t) at the time of the display. This UD is NOT in M since I calculate it FROM M. To show UD referential values I divide units by UD(t).
As you can see I get the average of 10 UD mb for each member as expected, with a c of 10%.

**Comment by galuel** [comment]
>Yes, M(t) is the sum of all the wallets at the current time. I take it from the last block, but it will not >change until the next UD will be added.

So it is not M(t) you display, but M(t+1) this is a first point.

>it is now, the current time at the moment of the display.

So this will lead you to problems. Imagine I1 make an invoice I2 with 3 DU = n MB, when I2 will check it at his time 3 DU will not be n MB, because it is DU(t+x) used, and so it depends on the time you check it between "t" and "t+1". If you use DU(t+x) so you need to display DU(t+x) and not DU(t), with the definition of t = the discrete time where DU is calculated by the blockchain.

So you need clear definition and clear display. For instance "t" you use now is not the definition used in http://www.metab.ucoin.io/#/home who use the discrete definition.

>N(t) is the number of members validated in the last block of the blockchain. So at the time of the >display.

So you must display "N(t+x)=..." or "N(now)=..." and not "N(t)=...".

>At the time "t" of the display, I am sure of the M value and the N value because for me they are >valid in the last block.

Those values, and the coherence between values (M,N,DU)(t) and (M,N,DU)(t+1) depend of discrete time "t", and not a continuous one where some of theese value change (N(t+x) alway can change), and other don't change (M and DU change at discrete points only).

In a discrete function you can need  values at "t" and "t-1" or "t+1" to calculate differential values (and much more if you need to calculate more differential degrees).

>Based on this values, I calculate the UD(t) at the time of the display. This UD is NOT in M since I >calculate it FROM M. To show UD referential values I divide units by UD(t).
>As you can see I get the average of 10 UD mb for each member as expected, with a c of 10%.

Yes it is ok but then you need to display correct variables : 

UD(t+x) which is not the last UD(t) everyone can see in his transaction tab, neither UD(t+1) which can also be different. It will be difficult to explain that.

N(t+x) and M(t+1) because you use M(t+1) and not M(t). Just before "t" you have M(t), and just after "t" UD(t) is calculated by the blockchain and added to M(t) to give M(t+1).

**The definition of UD(t) is : what it is added to members accounts from M(t) to obtain M(t+1).**

That is to say M(t+1) = M(t) + N(t)*UD(t), or M(t) = M(t-1) + N(t-1) DU(t-1)

What you can do to avoid to define a new time variable "t+x" is to display : 

M(present) = M(t) = M(t-1) + N(t)*DU(t) = ... MB
N(present) = ... members
M/N(present) = ... MB/members
DU(present) = Max[DU(t);c*M(t)/N(present)]

And use DU(present) for any relative view. But doing so, different people will have different view if they look at different time with N(present) that change between them, calculating different DU(present) and will not be ok between them.

This will also differ from the blockchain and the discrete time protocol and I am not sure different clients integration will differ from the database and protocol like this.

--- another way, following discrete time and uCoin protocol is to use discrete time only ---

**Last "t" verification point** : 
Last calculation time t = ... date / hour / minutes / seconds
M(t-1) = ... MB
N(t) = ... MB
DU(t) = ... MB
M(t-1)/N(t) = ... MB / members

** Next t+1 point **
Next calculation time = t+1 = ... date / hour / minutes / seconds
DU(t+1) = Max[DU(t);c*M(t)/N(t+1)] = protocol formula (= not continuous variation)

** now **
M(t+1) = ... MB
N(now) = ... members
DU(computed) = ... MB = Max (... MB; 10%/day * ... MB / ... members) (for information only)

And always use only DU(t) for any relative view, so all people will have same relative view.

Because people will see DU(t) in their transaction tab, it will be difficult to explain you use DU(present) to make calculation (although it can be mathematically correct). They probably will check calculation with the DU(t) they see in their transactions, and so will not understand what's happening when controlling.

**Comment by vtexier** [comment]
>The definition of UD(t) is : what it is added to members accounts from M(t) to obtain M(t+1).

That definition does not reflect the UD block generation of ucoin as explained in the protocol : 

**UD(t+1) = CEIL(MAX(UD(t) ; c * M(t) / N(t+1) ))**

Here we have UD(t+1) added to M(t) to get M(t+1)...

So if we say that LAST UCOIN UD BLOCK TIME is "t" then it contains : 

* M(t) = Monetary mass including UD(t)
* UD(t) = Calculated on M(t-1) and added to M(t-1) to obtain M(t)
* N(t) = Nb of members included those of this block, used to calculate UD(t)

So my very first screenshots showing M(t), N(t) from the last block does not seems wrong to me.
And calculating live the UD(t+x, or t+1 or present) based on M(t) to have relative referential give accurate results on display.

Furthermore, all the display is based on the only last valid block of the blockchain so every users will see the same thing. If not, it means that their client is not synchronised correctly with the blockchain.

**Comment by galuel** [comment]
>UD(t+1) = CEIL(MAX(UD(t) ; c * M(t) / N(t+1) ))
>Here we have UD(t+1) added to M(t) to get M(t+1)...

Yes I've written it wrongly, what it is added to M(t-1) to obtain M(t), it's true.

>So if we say that LAST UCOIN UD BLOCK TIME is "t" then it contains :
>M(t) = Monetary mass including UD(t)
>UD(t) = Calculated on M(t-1) and added to M(t-1) to obtain M(t)
>N(t) = Nb of members included those of this block, used to calculate UD(t)

I don't know if last uCoin UD blocktime (t) contains M(t) or M(t-1), or if M(t) is a calculated value from the blockchain list.

>So my very first screenshots showing M(t), N(t) from the last block does not seems wrong to me.

I don't know what is "last block", is it the last uCoin UD blocktime "t" ? Or is it later block ? If it is later block, you don't display N(t) but N(current) which is different.

>And calculating live the UD(t+x, or t+1 or present) based on M(t) to have relative referential give >accurate results on display.

Depends of what you mean by "display". In the "transactions" tab people will see UD(t) and UD(t+1) so they won't understand what is this UD(t+x) you display, it cannot be UD(t) neither UD(t+1) so what is it else than UD(computed) which I'm not sure it is an accurate value for people, because it does not fit with what they can control in transactions ?!

>Furthermore, all the display is based on the only last valid block of the blockchain so every users >will see the same thing. If not, it means that their client is not synchronised correctly with the >blockchain.

You don't think about the economy and the money when you say that. People won't see the same thing, and they won't understand what is all that curious thing !

Imagine the DU is calculated every 20 days. Then you ask for payment in 1st day "3 DU to pay before next DU", people will say "ok, he ask me 3 current DU, I can check it is 3000 MB" I will pay next week, it is still before next DU. 7 days after, N(t+x) has changed, so DU(current) will be no more 3000 MB, but only let's say 2900 MB.

People won't agree at all of what it is "3 DU", because you destroy the discrete way to do it, that assure DU is the differential value between discrete time from "t" to "t+1" so it is absolutely fix between two steps.

Because of discrete change of N(t), it is absolutely necessary to understand why calculation cannot be something else that discrete changes, and not continuous ones.

**Comment by vtexier** [comment]
Ok, I think I understand what you mean by discrete/continuous in that context.
So the problem I need to deal with is with N.

N is the only value that can change between each UD block, but I can only use the N of the last UD block.

I want to had to my display/calculate problem another one : display the current monetary mass, an important information that the users will ask for.

So I will think about a solution to all that...

Thank you for your precious help and your patience.
Stay tuned !

**Comment by galuel** [comment]
What is for sure necessary is to make clear distinction between t-1, t, t+1, and t+x = current time = computed, and to be clear when displaying and calculating with Numbers(t-1,t,t+1,computed).

**Comment by vtexier** [comment]
Now, relative values are calculated by dividing with the computed UD(computed) from the values at time t given in the last UD block : M(t), UD(t) and N(t).

All values are accurate, and, most importanty, also on wallets.

![cutecoin_units](https://cloud.githubusercontent.com/assets/2174016/8266861/92f76450-1745-11e5-8667-2f3f130beb03.png)
![cutecoin_ud](https://cloud.githubusercontent.com/assets/2174016/8266860/92e07ce0-1745-11e5-9dd8-018535886c2e.png)

**Comment by galuel** [comment]
It is not correct. DU in relative cannot be something else than 1.

growth calculation must be DU(t)/(M(t-1)/N(t)) or DU(computed)/(M(t)/N(current)) so display is not correct.

If there is display of N(t), then it should be also display of N(current).

So there should be 2 subtabs, tab with "t" data including M(t-1), UD(t), N(t) and tab with "current data" with M(t) DU(computed) and N(current).

Relative values should be calculated with UD(t) and not UD(computed) that will give different views for users if they check at different times between "t" and "t+1".

**Comment by vtexier** [comment]
All referentials values are now based on UD(t), N(t) with t = last UD bloc time.

![cutecoin_units](https://cloud.githubusercontent.com/assets/2174016/8271272/ce7e2bfc-180e-11e5-86fa-351289a5841f.png)

![cutecoin_ud](https://cloud.githubusercontent.com/assets/2174016/8271273/ce7f31a0-180e-11e5-8163-fa24e45bfa14.png)

Can I close the issue ?

**Comment by galuel** [comment]
Yes to me it seems 100% ok.

**Comment by vtexier** [comment]
done in f448e988bbe1697f4bd83561339ce8a675da094f
