### ISSUE TITLE
Have a classic bank account view

### ISSUE THREAD

**Issue by vtexier** [ucoin-io/cutecoin#15]
* Transactions should be displayed like any bank account report, as a table of columns : 

Date           | UID/Public key | Payment | Deposit | Comment
---------------|-------------------|--------------|-----------|------
2014-12-30 | John Doe       | 50           |              |
2014-12-31 | henry Smith   |                |        100 | For your birthday

* Clik on the column header to sort by this column ascending/descending...

* At the top of it, we should choose a start date and an end date for the period to display (buttons with calendars).
* Additionnal buttons to quickly display "this month" "this quarter" "this year"...

* Add a selector to display in the four referencing systems ("units", "UD", "units to zero", "UD to zero"...)

**Comment by Insoleet** [comment]
Added in https://github.com/ucoin-io/cutecoin/commit/798434ed4cba4cf8545f021502e2324da0cc0fb8
