### ISSUE TITLE
Error about next UD in Information Tab

### ISSUE THREAD

**Issue by Thatoo** [ucoin-io/cutecoin#157]
In Information Tab, it says that the next UD will be the 20/06/2015, but we are already the 23rd of June.

![erreur prochain du](https://cloud.githubusercontent.com/assets/464782/8306867/ee5a7000-19c3-11e5-9903-1591dff48df7.png)

**Comment by M5oul** [comment]
In fact, thanks for the report.

**Comment by Insoleet** [comment]
@vtexier got the same bug some week earlier. I wonder if his work on the informations tab fixes it.

Anyway, this will be hard to fix for 0.10.0 due to bad core code. I hope it will solved by itself for 0.11.0.

**Comment by M5oul** [comment]
This bug came surely from the issue on the network witch is stuck on a block generated 20/06/2015.

**Comment by Insoleet** [comment]
I guess it is fixed ?

**Comment by M5oul** [comment]
Think no. It display 25/06/2015 13:36 which was previous UD.

**Comment by Insoleet** [comment]
@vtexier, you got some time to look into this bug ?

**Comment by vtexier** [comment]
I have seen it again on 25/06/2015, it was one day late, but it was coherent with the api last ud block... I will check again ASAP.

**Comment by Insoleet** [comment]
Anyone sees it again now that blockchain doesnt stuck ?

**Comment by M5oul** [comment]
Seems ok for me on both branches.
