### ISSUE TITLE
Cutecoin is always launching in "maximize screen" mode

### ISSUE THREAD

**Issue by c-geek** [ucoin-io/cutecoin#161]
I like it opened in a little window :-)

**Comment by Insoleet** [comment]
@vtexier this is for you haha :)

**Comment by vtexier** [comment]
Personnaly, I prefer it to open in fullscreen, so may be we can have a vote on the ucoin forum ?
To avoid a fork of the project from @cgeek ;-)

**Comment by Insoleet** [comment]
Why not an options in preferences, "always start the window maximized" ?

**Comment by c-geek** [comment]
Yes plz a preference!

**Comment by Insoleet** [comment]
Done in https://github.com/ucoin-io/cutecoin/commit/fd08616fedf1d271dad109acdc0118ef984242bf
