### ISSUE TITLE
Menu Export

### ISSUE THREAD

**Issue by galuel** [ucoin-io/cutecoin#165]
fichier -> exporter ne mène nulle part.

(1) Une fenêtre s'ouvre pour choisir un répertoire apparemment, mais on ne peut pas saisir de nom de fichier, impossible d'exporter quoi que ce soit (qu'exporte-t-on d'ailleurs ? ce n'est pas clair).

(2) En bas le menu déroulant écrit "tout fichier de compte" et on ne voit pas d'extension de fichier.

Je pense que par défaut la fenêtre devrait s'ouvrir dans le répertoire où cutecoin sauvegarde les données du compte que l'on peut exporter / importer (lequel est-ce !? sous Ubuntu : ~./config/cutecoin)

**Comment by Insoleet** [comment]
Ok pour l'amélioration de la fenêtre d'export. 
Par contre, le ~/config/cutecoin n'est pas censé être utilisé / connu des utilisateurs standards. A terme il faut que ça soit transparent sans qu'il n'ait besoin de savoir ou se trouvent les données mises en cache.

**Comment by galuel** [comment]
A voir si ces données son sensibles ou pas. Si elles sont sont sensibles il vaut mieux que l"utilisateur sache où elles sont en cas de besoin de les supprimer (ex : changement de machine pour gérer son compte, nécessité d'effacer les données de l'ancienne machine...).

**Comment by Insoleet** [comment]
Disons que je préfère maitriser le processus, l'import/export est là pour ce cas d'usage.

Copier/coller des données y compris celles en cache, je suis pas très fan. Pas de garantie sur le comportement de cutecoin suite à une telle manipulation. Ca peut marcher dans 90% des cas mais je ne sais pas si ça sera 100% !

**Comment by galuel** [comment]
Clairement l'import - export est une fonctionnalité essentielle sous cette forme. Mais savoir où sont les données ne serait pas un luxe tout de même. Quitte à ce que ce soit dans le help, online ou pas.

**Comment by Insoleet** [comment]
Ok pour documenter tout ça. De toute façon il faudrait qu'on enrichisse la doc développeurs pour capitaliser les connaissances sur le long terme.
