### ISSUE TITLE
exception with nodes at block zero

### ISSUE THREAD

**Issue by vtexier** [ucoin-io/cutecoin#171]
>
Traceback (most recent call last):
  File "/home/vit/Documents/dev/python/cutecoin/src/cutecoin/core/registry/identities.py", line 66, in <lambda>
    reply.finished.connect(lambda: self.handle_lookup(reply, identity))
  File "/home/vit/Documents/dev/python/cutecoin/src/cutecoin/core/registry/identities.py", line 109, in handle_lookup
    data = json.loads(strdata)
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)

Some nodes are at block zero. ucoind version is not displayed for those nodes.
My certifications are wrong in the wot.
One identity has renew date at start of unix time.

![cutecoin_bug1](https://cloud.githubusercontent.com/assets/2174016/8572425/d0d5fe6c-258c-11e5-8c86-da6ba1ce7006.png)
![cutecoin_bug2](https://cloud.githubusercontent.com/assets/2174016/8572426/d0da5b56-258c-11e5-92ab-fe6ec0c671f2.png)

**Comment by Insoleet** [comment]
Multiple bugs there : 

- The network incorrectly thinks offline nodes are still online. Actually, no code exists right now to define nodes as offline... ;)  https://github.com/ucoin-io/cutecoin/blob/dev/src/cutecoin/core/net/node.py 
- Thought, requests are going to these offlines nodes and returns errors
- The errors are not handled in handle_lookup : https://github.com/ucoin-io/cutecoin/blob/dev/src/cutecoin/core/registry/identities.py

**Comment by Insoleet** [comment]
All bugs should be fixed with last commit.
