### ISSUE TITLE
members uid missing with new network crawling

### ISSUE THREAD

**Issue by vtexier** [ucoin-io/cutecoin#175]
Network crawling take some time to fill the uid column in members list.
And some members have no uid at all in the members list (here chaica and urodelus)...
As a consequence, when selecting them in the wot, the node is invisible ! and sometime exception arise.

![cutecoin_uid_missing](https://cloud.githubusercontent.com/assets/2174016/8618447/8f1a7b6e-270e-11e5-911f-354b0da9244c.png)

**Comment by Insoleet** [comment]
Probably linked to the cache problem. Can you try again with last commits ? Warning : the cache was probably corrupted due to mistakes, maybe you'll need to reset it.

**Comment by Insoleet** [comment]
I cant see this happen anymore with last commits. Can you ?

**Comment by vtexier** [comment]
Tested on dev branch, commit 3ce7a8bf355e1f06865fd2b1d398cdb2b82b2cce
Cache removed.
Got one uid missing...
![bug_uid_missing](https://cloud.githubusercontent.com/assets/2174016/9423172/98a82f2e-48b9-11e5-8a9d-83d8ff1a106e.png)

**Comment by vtexier** [comment]
Ignore that, after some (long...?) time, Jacques uid appears !
I've cleared again the cache, then restarted, and every uid are here... Closing !

**Comment by Insoleet** [comment]
What would be great, is if we could have a "loading symbol" instead of empty cells while downloading the data... Not sure if this is easy to do.
