### ISSUE TITLE
Bad cache refresh

### ISSUE THREAD

**Issue by vtexier** [ucoin-io/cutecoin#176]
Cache is stuck at 08/07/2015 UD, when the last block read is after 10/07/2015 UD.

So informations displayed are obsolete and the UD referential give 1.21 on last UD in transactions tab.

![cutecoin_infos_bug](https://cloud.githubusercontent.com/assets/2174016/8619082/19e4cd9e-2714-11e5-8dd3-1d69c97cc113.png)

**Comment by Insoleet** [comment]
The lasts fixes pushed should resolve the problem. Let's check the behaviour of the client in the following days...
