### ISSUE TITLE
Membership expiration date incoherence

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/cutecoin#177]
As you could see, expiration of my identity membership will expire 13 july 2015:

![wallet_tab_incoherent_membership_expiration_date](https://cloud.githubusercontent.com/assets/4758871/8621646/2542b13e-2727-11e5-8c1d-88c381f3d0fd.png)

But, in the WoT graphic, expiration of certifications is between 20 july and 6 august 2015.
![wot_incoherent_membership_expiration_date](https://cloud.githubusercontent.com/assets/4758871/8621640/210a9e4c-2727-11e5-8056-91383cdc9dba.png)

**Comment by Insoleet** [comment]
I'm not sure this is a bug. The membership expiration is distinct from the certifications expiration.

**Comment by vtexier** [comment]
It is not a bug. It is your membership expiration, as ucoin understand it, that is, your decision to be part of the community. This status need to be renewed.
It is separate from the certifications.
