### ISSUE TITLE
Certification issue

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/cutecoin#180]
I can't certify `psycows` user:
![certif_issue](https://cloud.githubusercontent.com/assets/4758871/8655094/28d24714-298f-11e5-9870-939161b29d88.png)

I think It is be due to last commits. I don't think I had this problem before. It also happend on 0.10.1 stable version.

**Comment by Insoleet** [comment]
I think you are not a member anymore of the meta_brousouf community.

**Comment by M5oul** [comment]
Ok :smile:

**Comment by M5oul** [comment]
So there is an [incoherence in WoT graph](https://github.com/ucoin-io/cutecoin/issues/177):
![wot_incoherent_membership_expiration_date](https://cloud.githubusercontent.com/assets/4758871/8621640/210a9e4c-2727-11e5-8056-91383cdc9dba.png)
