### ISSUE TITLE
Display something when no longer a member

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/cutecoin#181]
I am not a member. But it was hard for me to know that I was not a member anymore.

**Comment by Insoleet** [comment]
The account status is displayed on the wallets tab. Isn't it enough ?

**Comment by M5oul** [comment]
Where?
![capture d ecran de 2015-07-14 20-45-14](https://cloud.githubusercontent.com/assets/4758871/8681689/48e9c52e-2a69-11e5-9d93-3f01b3b44b05.png)

**Comment by Insoleet** [comment]
Your last membership document expired on July the 13th, but yeah, something more obvious should be displayed.
