### ISSUE TITLE
Curious bug sending money to newcomer

### ISSUE THREAD

**Issue by galuel** [ucoin-io/cutecoin#183]
Curious bug, when trying to send money to a newcomer who had only 1 certification, the number of units appear to be a great negative number, and DU show 0000, impossible to send anything. See screencapture below.

When trying to change impossible to change unit box, and when changing DU value unit box doesn't change.

![jacques](https://cloud.githubusercontent.com/assets/5245398/8704505/b03f93e2-2b23-11e5-8632-11b4510dd049.png)

**Comment by c-geek** [comment]
I encounter a similar issue while trying to send money to Inso:

![image](https://cloud.githubusercontent.com/assets/969136/8711512/f5d0de50-2b52-11e5-815e-7b3f3d43bff0.png)

**Comment by Insoleet** [comment]
Ok we are being trapped in a dirty bug right now.

Our wallets are owning too much money. Cutecoin sets the maximum of the amount spinbox to the money owned by the wallet. This number is bigger than a 32 bits integer, and it breaks the spinbox. The native Qt spinbox only handle 32 bits integer, even on 64 bits platform...

The two fixes I can imagine right now are : 
- Really fast one : set the maximum to 32 bits maximum if the amount is too big
- Create a custom spinbox to handle 64 bits numbers

**Comment by galuel** [comment]
With a theory point of view whatever the number of bits you will choose, money will always be able to grow more ! :)

But if we plan a 10^9 maximum members of people within the money (in fact we saw with WOT than about 10^7 is enough, but let's go to the limits !), and so a low limit rate of 5% / an => 20 annual DU for M/N, and so M = 20 x 12 x 10^9 monthly DU, with a limit of 6 digits that are enough for a monthly DU (think about 9999,99 € / month is enough when we study experience facts), so the maximum number of units needed, with be in theory, with all M in only one account and will be : 

Max = 999999 x 240 x 10^9 ≈ 2,4*10^17 ≈ 2^58

So you need 58 bits maximum, with a 64 bits it will be ok.

When the DU go more than 8 digits > 99999999 units ≈ 2^27, uCoin could create next blocs going back to 6 digits > 999999 = 2^20 by eliminating the 2 last digits, and anyone will know which number of units it is by counting the number of periods this will occur.

Note than with a normal 10% / an grow, going from 6 digits to 8 digits, is multiplying by 100, and so this period corresponds to : 

n = ln(100)/ln(1+10%) = 48,3 years.

And so this is not an urgent stuff ;), since with 64 bits it will last [note 2^(64-58) = 2^6 = 64] : 64 x 48,3 years = 3091 years = much more time before you need to turn the digits back...

**Comment by Insoleet** [comment]
In fact, QDoubleSpinBox handles a float, it's maximum value is 2^127 on 32 bits platform, which is still ok.

We need to check for side effects before going on this fix, but if it's fine, let's release during the week.

**Comment by Insoleet** [comment]
Ok no more change is needed, even for 32 bits, because python3 int types automatically transforms int to long when needed. I will release.
