### ISSUE TITLE
Exceptions in 0.11.0 dev branch

### ISSUE THREAD

**Issue by vtexier** [ucoin-io/cutecoin#184]
After a few hours opened, cutecoin raise thoses exceptions : 

>
Traceback (most recent call last):
  File "/home/vit/Documents/dev/python/cutecoin/src/cutecoin/core/net/network.py", line 223, in handle_change
    self.nodes.remove(node)
ValueError: list.remove(x): x not in list

and this one repeatedly : 

>
QBackingStore::flush() called for  QWidgetWindow(0x19f54c0, name = "MainWindowWindow")  which does not have a handle. 
QBackingStore::flush() called for  QWidgetWindow(0x19f54c0, name = "MainWindowWindow")  which does not have a handle. 
QBackingStore::flush() called for  QWidgetWindow(0x19f54c0, name = "MainWindowWindow")  which does not have a handle.

**Comment by Insoleet** [comment]
The. Qt error is really weird. After a fast googling, it seems to be linked to multiscreen stations, or at least when plugging/unplugging a display. Do you have one of these?

**Comment by vtexier** [comment]
Nope.  I have just locked the screen.

**Comment by Insoleet** [comment]
Did the screen switch off at a moment ?

**Comment by vtexier** [comment]
The parameters of the screen saver is "switch off the screen after 5 minutes". So yes, I think so.

**Comment by Insoleet** [comment]
It seems to be a Qt5 bug. https://bugreports.qt.io/browse/QTBUG-46024
