### ISSUE TITLE
Display number of validations of certifications and transactions

### ISSUE THREAD

**Issue by Insoleet** [ucoin-io/cutecoin#193]
With the new multibranch feature, we should display a number of validated blocks since the certification was done. 
Where should his information be displayed ? Should it be displayed as a "Validated at 24%" or as a number like "12/34 validations" ? 

Also, what is the number of validations expected ? Should the user decide by himself ? Should it be the medium of all the validations expected by knew nodes ?

@c-geek , @M5oul , @vtexier , What do you think ?

**Comment by c-geek** [comment]
IMO, the expected number of validations should come from the network as it is the "authority" answering to our questions (do I own this amount? is this guy a member? etc.).

Plus, I wouldn't say confirmations behave in a linear way, i.e. each time a confirmation is made, it is more likely that we "divide" chances of fork. I don't know how to express it, this is just an intuition of mine.

**Comment by Insoleet** [comment]
Ok. So we should check out the number of validations from certified nodes only. Should we choose the average number ? Or the maximum ? 

Cutecoin only requests synced nodes. With multibranch, synced nodes are considered to be the ones who have as the current block the majority of the current blocks known. We don't request all the branch, only the one used by a majority of nodes. Does that seems correct to you ?

**Comment by c-geek** [comment]
I would say we should take the *median* value.

The behavior about branches seems correct.

**Comment by Insoleet** [comment]
OK.

Where should this information be displayed ? A number on the arrows on the WoT tab for certifications not yet validated at 100% ? And for the transactions, a text color / background color going from red to black to show the validation ?

**Comment by c-geek** [comment]
Yep, that's OK.
