### ISSUE TITLE
Crash on View in Web of Trust

### ISSUE THREAD

**Issue by couillardcharles** [ucoin-io/cutecoin#198]
As a not accepted user when i click on "View in Web of Trust" for a user on the identities users list, i've a crash.
```bash
Traceback (most recent call last):
  File "/Users/charles/tmp/cutecoin/cutecoin/src/cutecoin/gui/community_tab.py", line 158, in view_wot
    self.wot_tab.draw_graph({'text': person.uid, 'id': person.pubkey})
  File "/Users/charles/tmp/cutecoin/cutecoin/src/cutecoin/gui/wot_tab.py", line 92, in draw_graph
    path = graph.get_shortest_path_between_members(person, person_account)
  File "/Users/charles/tmp/cutecoin/cutecoin/src/cutecoin/core/graph.py", line 61, in get_shortest_path_between_members
    path = self.find_shortest_path(self._graph[from_person.pubkey], self._graph[to_person.pubkey])
KeyError: '3fhkwCegXZKxtYb8gzgeLoALZjGRLDeNMApwcpQnC3Ff'
[1]    61568 abort   
```
The KeyError is my public key.

Platform: Mac Os
Version: master branch

**Comment by Insoleet** [comment]
This is probably a crash due to pyqt 5.5. Before it was not crashing so some exception were missed. Since 5.5 any exception in the qt environment will abort python..

Can you try with the dev branch ? Not so much devs and fixes will be done on master branch now since they will be most probably lost development, due to major code change between 0.10 and 0.11...

**Comment by vtexier** [comment]
You are the first to manage to run cutecoin on Mac OS ! Please can you describe step by step all the process to install cutecoin on a mac OS on the forum?

http://forum.ucoin.io

We will include this in our wiki.

Furthermore, could you try to build a binary for mac os ?

**Comment by vtexier** [comment]
I confirm the bug. May be the asynchronous behavior of the get_certified/certifiers need to refactor the code using it...

**Comment by Insoleet** [comment]
It is still happening after last night commits ?

**Comment by vtexier** [comment]
No. No more crash. But now, browsing in the wot display a loading circle, and it takes at least 15 seconds to update the wot...

**Comment by Insoleet** [comment]
Yes this is the time to request the network with all the data. Once data are refreshed, it's way faster, thought. (Data are downloaded only once, when the block just changed).

**Comment by Insoleet** [comment]
Is this bug fixed ? I never encountered it again for some time...

**Comment by Insoleet** [comment]
It happened again : 


```
ERROR:main:async_exception_handler:Task exception was never retrieved
future: <Task finished coro=<draw_graph() done, defined at /home/inso/code/ucoin/cutecoin/src/cutecoin/gui/wot_tab.py:185> exception=KeyError('8Fi1VSTbjkXguwThF4v2ZxC5whK7pwG2vcGTkPUPjPGU',)>
Traceback (most recent call last):
  File "/home/inso/.pyenv/versions/3.4.3/lib/python3.4/asyncio/tasks.py", line 238, in _step
    result = next(coro)
  File "/home/inso/code/ucoin/cutecoin/src/cutecoin/gui/wot_tab.py", line 234, in draw_graph
    path = yield from graph.get_shortest_path_between_members(identity, identity_account)
  File "/home/inso/code/ucoin/cutecoin/src/cutecoin/core/graph.py", line 91, in get_shortest_path_between_members
    self._graph[to_identity.pubkey])
KeyError: '8Fi1VSTbjkXguwThF4v2ZxC5whK7pwG2vcGTkPUPjPGU'
```

Everytime, the user pubkey is the key missing from the dictionary.
