### ISSUE TITLE
41 DU MB

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/cutecoin#199]
![cutecoin41dumb_home](https://cloud.githubusercontent.com/assets/4758871/9578288/ca3ebe8c-4fe8-11e5-9343-be5eaf4e929d.png)
![cutecoin41dumb_tx](https://cloud.githubusercontent.com/assets/4758871/9578287/ca3c97e2-4fe8-11e5-9523-85127efb7c7f.png)
![cutecoin41dumb_network](https://cloud.githubusercontent.com/assets/4758871/9578289/ca3f6c88-4fe8-11e5-9c0b-60ba5ccb1d58.png)

**Comment by Insoleet** [comment]
The network forked hard and cutecoin does not know where to get the correct informations.

At the moment we are only using the majority block as the current block. Maybe other properties could be used to choose the current block, in the following order : 
- 1 : The block of the majority
- 2 : The more difficulty
- 3 : The more last different issuers
- 4 : The biggest number or timestamp

What do you think, @c-geek ?

**Comment by c-geek** [comment]
I think your proposition is what I would do, except I would switch 2) and 3).

**Comment by Insoleet** [comment]
Should not happend anymore. Can you check, Moul?

**Comment by M5oul** [comment]
Seems ok for me.
