### ISSUE TITLE
Add a "About" window

### ISSUE THREAD

**Issue by Insoleet** [ucoin-io/cutecoin#20]
An "about" popup should be available under a "?" menu in the main window.

The about popup should display the current version, the software license, and the authors.

**Comment by vtexier** [comment]
done in 059bda49ab2caae893f109183e6c97788bf157b3

**Comment by Insoleet** [comment]
In which branch did you push it ?

**Comment by vtexier** [comment]
ooops.
Branch was not pushed.

Pushed with the name "about_popup".
