### ISSUE TITLE
Can't display many accounts in differents tiles

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/cutecoin#201]

**Comment by Insoleet** [comment]
Yeah, we will look after this bug after the UI Refactoring since the behavior of cutecoin will change a lot.

**Comment by Insoleet** [comment]
You can try the behaviour now.

**Comment by M5oul** [comment]
I can't display many tiles as in:
![beta_mainwindow](https://cloud.githubusercontent.com/assets/1170293/9487341/eb189cde-4bd0-11e5-95fd-3cf9db975522.png)

![new_ui_mb](https://cloud.githubusercontent.com/assets/4758871/9672583/4f3538ea-529c-11e5-9e89-a649b544a0db.png)
![new_ui_fm](https://cloud.githubusercontent.com/assets/4758871/9672584/4f35a168-529c-11e5-8d27-702c9b98f5bb.png)

**Comment by Insoleet** [comment]
Can you try again pleases ?

**Comment by M5oul** [comment]
It does not works…

**Comment by M5oul** [comment]
Finally, it works. I removed then add the account. I can see many tiles :smile:
