### ISSUE TITLE
Can not certify other member when launching a new money.

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/cutecoin#203]
I can not certify other member with a new money. As I am not a member, I can not certify other member. How did we launched `metab_brouzouf`?

**Comment by Insoleet** [comment]
With cutecoin, but an older version. Check the releases dates and the meta_brouzouf start date. ;)

**Comment by M5oul** [comment]
Ok :smile:

**Comment by Insoleet** [comment]
This should work now...

**Comment by M5oul** [comment]
Great! We need to try it :smile_cat:
