### ISSUE TITLE
Develop tests using pretenders

### ISSUE THREAD

**Issue by Insoleet** [ucoin-io/cutecoin#204]
We should develop unit tests or functionnal tests by using the pretenders library : 
https://pypi.python.org/pypi/pretenders/1.0.2

This can mock REST API in local python code. We can thus initialize mocked ucoin server "on the fly" in our tests and request it to check what cutecoin display and how it reacts.

This can even be used to do TDD for future ucoin versions.

@vtexier this should be interesting ;)

**Comment by vtexier** [comment]
Indeed, with a fake server we really test what is send from cutecoin.

**Comment by Insoleet** [comment]
https://github.com/ucoin-io/cutecoin/tree/mocks

Checkout the developed tests and please tell me what you think about it ! :)
