### ISSUE TITLE
Remove account button

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/cutecoin#205]
It would be great to have a button to remove an account from CuteCoin.

**Comment by Insoleet** [comment]
It already exists, you have to configure your account then click on "Delete this account".

**Comment by M5oul** [comment]
Ok. A bit hard to find.

**Comment by Insoleet** [comment]
Yes It is not supposed to be easy to remove an account... Should not happen often ^^

**Comment by M5oul** [comment]
Yep :wink:
