### ISSUE TITLE
Connecting/Register to a community should check for the UID

### ISSUE THREAD

**Issue by Insoleet** [ucoin-io/cutecoin#214]
0.11 is only looking for the pubkey. We should also check for the UID.

If the UID is present but with a different pubkey, we should raise an error.
If the pubkey is present but with a different UID, we should raise an error too.

The problem should be explicitly explained.

**Comment by Insoleet** [comment]
@M5oul, can you do some review on the feature please ? :)

**Comment by M5oul** [comment]
After a cache cleaning, I think I can add the fair_money account anymore and I could add the meta_brouzouf account.

**Comment by Insoleet** [comment]
Any message ?

**Comment by M5oul** [comment]
Nope!

**Comment by Insoleet** [comment]
Maybe it was related to the Identities registry bug I fixed this morning...
