### ISSUE TITLE
Can't get many tiles

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/cutecoin#215]
I can't get many tiles on same screen. I think to do so, it may be possible to add other account with `Add an account` button. When I click on it, I only get address and port asking and not account name. That's why it doesn't add new account.

By the way, it would be better to get only on button to add an account, it is confusing.

First screen is almost useless:
![welcome_button](https://cloud.githubusercontent.com/assets/4758871/9965717/587e0dd0-5e38-11e5-937d-bca224d4c39b.png)

For me homescreen should be the one with tiles.

Why did you do two screens, the home one and the tiles one?

**Comment by Insoleet** [comment]
The tile screen and what you call the home screen are the same. You select the account you want to use, and the tiles are displayed depending on this account. You would like to be able to display multiple account on the tiles screen ? That would begin to be complex...
