### ISSUE TITLE
Network behavior

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/cutecoin#217]
Is this network behavior is right with an issue on blocks sharing. It stay stucked on old blocks.
![network_behavior](https://cloud.githubusercontent.com/assets/4758871/9975942/c68b8f9a-5ecf-11e5-9445-9e55b997dabd.png)

**Comment by Insoleet** [comment]
Yes it's normal, cutecoin select the block which is the best consensus in the network. So, the block used by the majority of the nodes.

**Comment by M5oul** [comment]
Ok.
