### ISSUE TITLE
Error: transaction from signature must match

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/cutecoin#218]
I have try to send money, I get that: `Error: transaction from signature must match`. I only get that issue when sending money to cgeek.

**Comment by Insoleet** [comment]
@c-geek there is a typo in your error if this is written this way ! ^^ `mach` :) 

When is this error present ? I can't reproduce it. Could it be because of your double UIDs cgeek ?

**Comment by c-geek** [comment]
Moul probably hand wrote the sentence. In the code the error is:

> Signature from a transaction must match

Anyway, this error occurs when signature is invalid. The range of causes that may lead to this is very large...

**Comment by M5oul** [comment]
Yep, match.

This problem did not appear again.

**Comment by Insoleet** [comment]
To be continued...
