### ISSUE TITLE
Network: some nodes are wrongly displayed red

### ISSUE THREAD

**Issue by c-geek** [ucoin-io/cutecoin#219]
The *member* node is always displayed in red after few minutes waiting:

![image](https://cloud.githubusercontent.com/assets/969136/9977327/0df99dee-5f03-11e5-9c78-8e017e3c5b14.png)

If I manually actualize the network view (acutalize button), then the line becomes green again:

![image](https://cloud.githubusercontent.com/assets/969136/9977332/3a54230a-5f03-11e5-8588-25a3a2666c07.png)

If I wait a bit more and a new block is spread across the network, then the node becomes red again:

![image](https://cloud.githubusercontent.com/assets/969136/9977337/6350132c-5f03-11e5-83f1-fb22b1e3c342.png)

Waiting a bit more put it *automatically* in green again.

![image](https://cloud.githubusercontent.com/assets/969136/9977346/0087f2fe-5f04-11e5-8736-191fd38731ae.png)

And few moments later it becomes red again...

![image](https://cloud.githubusercontent.com/assets/969136/9977351/34482672-5f04-11e5-916c-8a524d57897c.png)

Obviously something strange is happening here. Maybe, as this is my computing node, the answer take a bit too much time to come back.

**Comment by c-geek** [comment]
I forgot to say: the button always result in the same behavior: the line becomes/stays green.

**Comment by Insoleet** [comment]
This is really weird because I can't reproduce it here.... There is probably a request raising an error on this node. Some logs would probably be needed.
Can you look for "Client error" or "Timeout error" in your cutecoin.log file ?

**Comment by Insoleet** [comment]
Ok I reproduced this behaviour. After some checks,the cause of your node to go "offline" is timeouting on it's UID search. The timeout is 30 seconds...

**Comment by c-geek** [comment]
Yes, I managed to find it:

	DEBUG:__init__:Timeout error : HnFcSms8jzwngtVomTTnzudZx7SHUQY8sVE1y8yBmULk
	DEBUG:__init__:HnFcS | Last state : 1 / new state : 2
	DEBUG:__init__:HnFcS | Changed state : 1442741025.622198
	DEBUG:__init__:00001AD725 -> 00001AD725
	DEBUG:__init__:Refresh block
	DEBUG:__init__:Refresh info
	DEBUG:__init__:Refresh uid
	DEBUG:__init__:Refresh peers
	DEBUG:__init__:Refresh summary

This might be linked to the fact I am currently in the countryside (ping 37ms), but that is still weird this error only occurs on *member* node. Maybe this is the result of my node being busy to compute blocks, but this process is precisely in another process so that it doesn't block the main thread.

**Comment by c-geek** [comment]
Ok, so indeed I have a 504 Gateway timeout on: http://metab.ucoin.io/wot/lookup/cgeek

**Comment by Insoleet** [comment]
On the pubkey too : http://metab.ucoin.io/wot/lookup/HnFcSms8jzwngtVomTTnzudZx7SHUQY8sVE1y8yBmULk (the UID is checked after the pubkey of the node)
