### ISSUE TITLE
Need for "lookup" box to certify someone who isn't a member

### ISSUE THREAD

**Issue by c-geek** [ucoin-io/cutecoin#23]
Currently, I can't certify someone using the search box in Community > WoT that is not a member yet.

Could we have such feature?

**Comment by Insoleet** [comment]
Yeah sure

In the meantime you can still certify a known pubkey !

**Comment by vtexier** [comment]
Done in the wot branch...

**Comment by Insoleet** [comment]
Did you push it to the repository ?

**Comment by vtexier** [comment]
Yep : 
https://github.com/ucoin-io/cutecoin/commit/94412310079fedc5f4175fd77cbe0b64ebc02627

**Comment by vtexier** [comment]
Search in wot return non members as well in release 0.7.5
