### ISSUE TITLE
WoT view has random behavior

### ISSUE THREAD

**Issue by c-geek** [ucoin-io/cutecoin#231]
Consider this:

![image](https://cloud.githubusercontent.com/assets/969136/10279203/dcdd9888-6b63-11e5-9f37-d800eee9300f.png)

When I click again on "tierce", I often obtain this:

![image](https://cloud.githubusercontent.com/assets/969136/10279210/ea704e14-6b63-11e5-9c8c-10c178986bb9.png)

And if I click again, I may obtain screen 1 or screen 2, and so on.

There is only one identity "tierce" on the nodes.

**Comment by Insoleet** [comment]
This can happen if tierce is not in the blockchain but only in the UID pool. Also, can certifications be present in the nodes pools if the user is not in the blockchain yet ?

**Comment by c-geek** [comment]
Yes, it is possible and event frequent. You can make a certification without being a member, which will be integrated later when you become a member.

**Comment by Insoleet** [comment]
Then this would explain this information.

I guess we should display a "0/[fork window + 1] validations" when the certification comes from the node pool.
