### ISSUE TITLE
Ghost identities

### ISSUE THREAD

**Issue by c-geek** [ucoin-io/cutecoin#232]
Some identities does not have an UID according to Cutecoin, like this one:

![image](https://cloud.githubusercontent.com/assets/969136/10315592/81343278-6c5b-11e5-8a8b-593d75401f5e.png)

However I do see it has an UID here: http://metab.ucoin.io/wot/lookup/KaCee

Might it be linked to the fact KaCee is not on another node? http://metab.ucoin.io:9212/wot/lookup/KaCee

**Comment by Insoleet** [comment]
It is probably linked to the fact that KaCee is not on another node.
We try 3 times to find an UID (3 random tries, can be 3 times the same node).

**Comment by M5oul** [comment]
I don't encounter that issue. The identity which is not displayed and sign by `tierce` and `smoul` seems to be `fatalas`:
![wot_issue](https://cloud.githubusercontent.com/assets/4758871/10318042/c1b7306e-6c67-11e5-9141-ff4fd81521d4.png)
![wot_isuse_2](https://cloud.githubusercontent.com/assets/4758871/10318041/c193f914-6c67-11e5-8b77-54d1c7dfdd2c.png)

**Comment by Insoleet** [comment]
Yes M5oul, it's mostly random.

It could be enhanced thought, be cause when we successfully downloaded the certifiers and certified identities, we could have find the UID of the user at this time.
