### ISSUE TITLE
Zero-sized fork window and certifications

### ISSUE THREAD

**Issue by c-geek** [ucoin-io/cutecoin#244]
Launching Cutecoin this morning, I could see I had 3 certifications with "0/1" confirmations:

![image](https://cloud.githubusercontent.com/assets/969136/10877702/c4d178f4-8148-11e5-8fe7-912678850977.png)

However, I *know* these certifications are already written in every node of the network (it is written in the blockchain).

Shouldn't cutecoin directly write 1/1, or just nothing like in this screen?

![image](https://cloud.githubusercontent.com/assets/969136/10877715/ef262096-8148-11e5-87f4-f563cfa63cea.png)

**Comment by Insoleet** [comment]
It should be nothing like in the second screen. It's a bug :)

**Comment by Insoleet** [comment]
Fixed.
