### ISSUE TITLE
Some non-members appear as members in WoT view

### ISSUE THREAD

**Issue by c-geek** [ucoin-io/cutecoin#245]
For example, kimamila is not a member here:

![image](https://cloud.githubusercontent.com/assets/969136/10890385/003ef480-8198-11e5-9de8-2919757e0b60.png)

But if I click on him, he is no more red circled:

![image](https://cloud.githubusercontent.com/assets/969136/10890394/0c8c9742-8198-11e5-955b-7d67fca1b2f3.png)

So I am a bit lost :grin: I guess he is not a member, but it is not clear!

**Comment by Insoleet** [comment]
I could not reproduce this... :( Can you, next time you got this bug, close cutecoin and zip your cache so that I can check what was in there ?

**Comment by c-geek** [comment]
I have an "old" build of cutecoin 0.11 also, this might have been fixed..

**Comment by Insoleet** [comment]
It seems to be fixed with latest debugs on the identities.
