### ISSUE TITLE
Network usage: try to make less requests

### ISSUE THREAD

**Issue by c-geek** [ucoin-io/cutecoin#249]
Currently Cutecoin is pulling data from servers.

It could prefer the [push APIs from BMA](https://github.com/ucoin-io/ucoin/blob/master/doc/HTTP_API.md#websocket) instead.

**Comment by Insoleet** [comment]
We are requesting 5 kinds of data at the moment : 

 - Current block
 - Node peering
 - Node identity
 - Peers
 - Node software & version

Block & Peers can be requested throught push API. 
For the 3 others data, they could be forced to be refreshed through the "refresh" button. Automatically, it could be one time a day maximum, or maybe even less ?

**Comment by c-geek** [comment]
Yes, even 1 time an hour is OK.

**Comment by Insoleet** [comment]
Ok, for cutecoin 0.11, I won't implement websockets. Only the following : 

- Refresh blocks & peering every 15 seconds
- Refresh every other data at cutecoin startup then every hour
