### ISSUE TITLE
UD date incoherence

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/cutecoin#253]
We are the 10th november and cutecoin stay stucked on an old UD(6 november):
![du_date_incoherence](https://cloud.githubusercontent.com/assets/4758871/11075119/d1b4538c-87f3-11e5-8f27-9d768cb41d42.png)

You could see UD > 1:
![du_incoherence_date](https://cloud.githubusercontent.com/assets/4758871/11075151/0dff9630-87f4-11e5-95c7-e20b21c429b9.png)

It could be due to the fact that I added my node.

**Comment by Insoleet** [comment]
It seems to be due to uCoin nodes returning a bad "with/ud" answer : 
http://metab.ucoin.io/blockchain/with/ud
The latest with/ud block is 39701

http://moul.re:8999/blockchain/with/ud
The latest with/ud block is 40115

@c-geek what do you think about it ?

**Comment by Insoleet** [comment]
So it's a ucoin bug.
