### ISSUE TITLE
WoT display is not updated when blocks are received

### ISSUE THREAD

**Issue by c-geek** [ucoin-io/cutecoin#262]
Consider following screenshot:

![image](https://cloud.githubusercontent.com/assets/969136/11324113/06c23246-9128-11e5-827a-2d549ccf5060.png)

I had to manually click on "rougailsaucix" to have cutecoin display "4/26".

**Comment by Insoleet** [comment]
You can enable auto refresh in the parameters ! :)

**Comment by c-geek** [comment]
Ok you got me on this one! I even didn't have to restart cutecoin. Good job. :smile:
