### ISSUE TITLE
Fact validation calculation

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/cutecoin#267]
For transaction and certification validation, I don't understand why had been chosen this calculation:
```bash
Fact validation = (current block number - block number containing the fact) / nodes median blockchain forksize.
```

`blockchain forksize` is the capability of a node to save n blocks of an other branch of blockchain.

For me this calculation doesn't make sense. In my point of view, we should calculate fact validation with this calculation:
```bash
Fact validation = fact presence number in nodes blockchains (including forks) / running nodes number
```

What do you think about that?

**Comment by Insoleet** [comment]
Because in the blockchain, the validation (that we should call *confirmation* to use blockchain vocabulary) is the number of blocks issued since the transaction was written in the blockchain. More the blocks, the less it is possible for the transaction to be present in a dropped blockchain branch.

**Comment by M5oul** [comment]
Ok, it's a defensible argument.
