### ISSUE TITLE
Cannot add a Community if remote node doesn't have a blockchain

### ISSUE THREAD

**Issue by c-geek** [ucoin-io/cutecoin#27]
Trying to start a new currency, I cannot add a Community (in Account > Add menu > Add a community button).

When I select a node hostname + port and click on next, nothing happen.

**Comment by Insoleet** [comment]
Can you describe what is the state of a node without blockchain ?

**Comment by c-geek** [comment]
In such a case, all the API works the same way except that:

* `/blockchain/current` and `/blockchain/block/0` will return a 404
* `/network/peering` will return a Peer document whose "Block" reference is an unexisting block, a "blank block" that is always refered as `0-DA39A3EE5E6B4B0D3255BFEF95601890AFD80709`
* Same idea for Certifications and Memberships sending: Block reference must be `0-DA39A3EE5E6B4B0D3255BFEF95601890AFD80709` while no root block exists.

So it involves CuteCoin has to make the difference between started currency and non-started one both for 404 errors, but also for `0-DA39A3EE5E6B4B0D3255BFEF95601890AFD80709` block reference to put in Cert ification & Membership documents.

**Comment by Insoleet** [comment]
Fixed in https://github.com/ucoin-io/cutecoin/commit/22890673f09e243a7b8d721df713484261c88d7c
