### ISSUE TITLE
UD - Brouzouf

### ISSUE THREAD

**Issue by galuel** [ucoin-io/cutecoin#31]
It should be better to specify UD with currency index like : 

UD-meta brouzouf-

or

UD -mb-

or any other way to know which currency it's about.

**Comment by Insoleet** [comment]
In which dialog or window is it missing ?

**Comment by galuel** [comment]
It's missing in "wallet", in "transactions" and also in "transfer money" window. Like in Physics, it is always necessary to specify the unit of money you use. Imagine we have metabrouzouf (mb) and zetabrouzouf (zb), we always need to know exactly which unit is used when we watch it :

110 mb or 1,1 UD mb
110 zb or 1,1 UD zb

**Comment by Insoleet** [comment]
@c-geek , we need a way to have the currency name in a "short" name, like two or three letters....

**Comment by Insoleet** [comment]
Added in https://github.com/ucoin-io/cutecoin/commit/b566c4cdc027da9bfa3d800b86ccd224cdc30c03
