### ISSUE TITLE
Cutecoin do not refresh member's list or wot when we became member in a new block 

### ISSUE THREAD

**Issue by vtexier** [ucoin-io/cutecoin#32]
Cutecoin is open. The block is 96.
After asking for membership, and receiving enough signatures, I look again to see me in the member's list... but no. I am not in the list nor in the wot.
But the block in now 100.
I restart cutecoin and, for the same block 100, I finally appear in the wot and member's list.

**Comment by Insoleet** [comment]
The community has a different cache than Wallets, which is not refreshed by the BlockchainWatcher. It has to change.

**Comment by Insoleet** [comment]
Fixed in https://github.com/ucoin-io/cutecoin/commit/8d6dae1ccc942a6435dba819d1857156f600379b
