### ISSUE TITLE
free money => publish the money code

### ISSUE THREAD

**Issue by galuel** [ucoin-io/cutecoin#34]
il est nécessaire d'afficher le code de la monnaie dans cutecoin (la formule de calcul), le nombre de membres N, la valeur de "c" et M. Sans quoi la monnaie n'est pas libre.

Ce qui est noté sur https://github.com/ucoin-io/cutecoin/issues/new est parfait à ce titre.

**Comment by vtexier** [comment]
Galuel: speak english here... please.

parameters of the monney should be displayed to heve a real freedom monney.
With all (?) the parameters displayed here : 

http://www.metab.ucoin.io/#/parameters

**Comment by galuel** [comment]
Yes vtexier it is good, alle those parameters should be in cutecoin, but the formula of the money is not in the parameters, it's obvious we need it.

I suppose a specific window where all the parameters are collected. The user need them for the freedom to check the money code.

**Comment by vtexier** [comment]
My bad... So we need all this infos : 

* Variables of the money M,N, etc
* Rules of the money (c formula)
* Parameters of the money

like cgeek did here : 
http://www.metab.ucoin.io/#/home
http://www.metab.ucoin.io/#/parameters

**Comment by galuel** [comment]
Yes this is correct.

**Comment by vtexier** [comment]
May be the ucoin api need to be updated to send the c formula and other missing data...

**Comment by galuel** [comment]
You can obtain them here : http://metab.ucoin.io/blockchain/parameters

**Comment by vtexier** [comment]
cgeek tell me this : 
you can have M(t+1), N(t), UD(t) in http://metab.ucoin.io/blockchain/block/410, where 410 is the last block with UD (http://metab.ucoin.io/blockchain/with/ud). These variables are respectively monetaryMass, membersCount and dividend fields of the resulting block.

**Comment by galuel** [comment]
Separate informations about parameters of the Money code (M,N,t,c,UD...) and parameters of the WoT code (stepmax...) which are independant notions.

**Comment by vtexier** [comment]
Done in fcf23c37d8661582e1a02da835eb866b62958fbe
