### ISSUE TITLE
Missing dates

### ISSUE THREAD

**Issue by galuel** [ucoin-io/cutecoin#35]
We need to know within the client : the up to date time (year, month, day, hour, minutes). And also we need to know in the transaction tab, the date of each transaction, and by right clic on the ID, information of the receiver (pubkey, id, specific windows I suppose to collect the information of what is this account).

**Comment by Insoleet** [comment]
Done in https://github.com/ucoin-io/cutecoin/commit/ddb2361d37a2f9a3f54a592c776d49c6c16d3123
