### ISSUE TITLE
Quantitative, Relative

### ISSUE THREAD

**Issue by galuel** [ucoin-io/cutecoin#36]
I supposed the unit we put the information in the windows (Q or E, or Q with zero sum or any other referentiel future developpers would like to add), should be chosen by a button or within the menu, so by clicking on it, all information about the money units change from Q to R or from R to Q.

It is possible also to have 2 referentials on the window (or perhaps 3 or w, but will be difficult with great "x" !) , I suppose the best way then would be to have 2 colomns Q a R, for instance in transaction window : 

Q          |   R                  |      to
10 mb   |  0,1 UD mb    |      inso

then referential "Q" and "R" could be choosen by user as "Referentiel R1 = Q" and "Referential R2 = R", and possibly the user can choose in a list of referentials Q,R,QZ,RZ,WTF... which one he puts in column 1 and which one he puts in column 2. By default I suppose Q & R is a good choice.

**Comment by Insoleet** [comment]
What about a selector to chose which referential to display in the client ?

Like in the statusbar, a combobox ( http://manual.qooxdoo.org/1.3/_images/combobox.png ), where you can chose which referential to use, dynamically ?

**Comment by galuel** [comment]
Yes, this could be a very good feature.

**Comment by Insoleet** [comment]
Added in https://github.com/ucoin-io/cutecoin/commit/a96715caeaa18a3f0db484b2e24d3abbd7c1aab3
