### ISSUE TITLE
wot and user window

### ISSUE THREAD

**Issue by galuel** [ucoin-io/cutecoin#37]
The wot is made of : directly signed / signed by members, and far members (with distance > 1).

We need a user window, that can be used in many others (wot graph, list of members, contact...), where we can show to the user, informations about the member he clics on : 

uid, pubkey, distance, way to reach it (for instance kimamila - galuel is distance 3, you can reach it thru distance 1 : vit, cgeek, inso..., distance 2 : (clic on vit, cgeek, inso...), etc... until galuel is reached). Date of entrance in the community, time from entrance to now... any usefull information one can have about one account.

**Comment by vtexier** [comment]
Path between wallet member and selected member is now displayed in the WoT. Every other information are already displayed in the WoT or in the members table.
I will open an issue to add "entrance date" in the members table.

**Comment by vtexier** [comment]
Finally, I will make the "member" popup window displaying member properties.

**Comment by vtexier** [comment]
done in 2928a2bbebb77a75c9d52757b43a60ccdc08c04d
