### ISSUE TITLE
Wallet update only happens on 1 panel

### ISSUE THREAD

**Issue by c-geek** [ucoin-io/cutecoin#38]
I've just noticed that, when a new UD is available, the right panel of Wallet tab is well updated (I've seen a `100` number added in the list), but the left panel is not (I had something like 2.x UD, and had to reload my account to see 3.74 UD, which is the good number).

**Comment by Insoleet** [comment]
Fixed in https://github.com/ucoin-io/cutecoin/commit/4978fcbf75d0f158e6979c138de0baadb3ba502d
