### ISSUE TITLE
uCoin version too

### ISSUE THREAD

**Issue by galuel** [ucoin-io/cutecoin#40]
Cutecoin version AND uCoin version should be in the main window upbar.

**Comment by Insoleet** [comment]
Is there anyway to know ucoin version from bma, @c-geek ?

**Comment by c-geek** [comment]
Well ... I guess I can add a method in BMA, yes. I will.

**Comment by c-geek** [comment]
Feature added. You can test with http://metab.ucoin.io/node/summary for example.
