### ISSUE TITLE
WoT lookup box modifies my search

### ISSUE THREAD

**Issue by c-geek** [ucoin-io/cutecoin#41]
I wanted to look for `Kalmac`. I made a mistake and wrote `kalmac` (lower-cased `K`). So, I tried to type it right `Kalmac`. But cutecoin turns it to `kalmac`. So I can never find `Kalmac`, since it always searchs `kalmac`.

Well, if I type `cgeek`, I can then type `Kalmac`. But that's a bit tricky!

**Comment by vtexier** [comment]
You're right, it was a tricky one !
Bug fixed in dfee264b75b23effc23f161f7bedeac7656d5594

**Comment by Insoleet** [comment]
I wonder if we should release a 0.7.6 for the last few bugs or if we wait for 0.8.

**Comment by vtexier** [comment]
Sure we will release a 0.7.x with bugfixes, but we can wait to have a certain amount of bugs... As you see fit...
