### ISSUE TITLE
Could cutecoin remove cache without manual intervention?

### ISSUE THREAD

**Issue by c-geek** [ucoin-io/cutecoin#42]
When 0.7.4 was released, we had to manually remove _cache_ folder, for each identity we had.

Could cutecoin do it automatically? And/or may we have a "clear cache" button somewhere?

**Comment by Insoleet** [comment]
Done in https://github.com/ucoin-io/cutecoin/commit/d7f78e1a6b2fc08c780e8701f7958ad37107474e
