### ISSUE TITLE
Clic right in the "Members" tab => WoT & WoT search !?

### ISSUE THREAD

**Issue by galuel** [ucoin-io/cutecoin#44]
It misses the possibility in the "members tab" with right clic on a member a menu to go directly to the WoT tab where the member clicked is in the center.

Int he WoT tab the search of a member should be done after clicking a button, right now we need to push "enter" to dot it.

**Comment by vtexier** [comment]
Done in f7bb5b0b532052196c990288f6dded5dc323475c
