### ISSUE TITLE
Alert when new version

### ISSUE THREAD

**Issue by galuel** [ucoin-io/cutecoin#46]
I suggest the feature that cutecoin alert the user when a new version is available, and where to go to have instructions to download / install it.

**Comment by M5oul** [comment]
One time Cutecoin will be packages for distributions, the distributions package manager will manage the update easily. In fact, I am talking for free OS, but for non-free OS, it could be a good feature which will come later I think.

**Comment by Insoleet** [comment]
https://github.com/ucoin-io/cutecoin/commit/2f63bba7d1a5c8954e80b3d0a2ad15db275a1c49
