### ISSUE TITLE
When creating a first account, it should be immediatly opened and set as default

### ISSUE THREAD

**Issue by vtexier** [ucoin-io/cutecoin#48]
Starting from scratch with Cutecoin, if I create my account, nothing happens when the popup window closes. The main windows stays empty...
I must go to the menu and choose "open" to see my account.

Furthermore, if I quit Cutecoin and restart, my only account is not displayed, the main window is empty again...
I must go again in the menu to "open" my account.
I must select "set as default" to stop that...

So I think that when the first account is created, it should be automatically opened and "set as default".

**Comment by Insoleet** [comment]
https://github.com/ucoin-io/cutecoin/commit/a81d18bf6f76fa57cc42b948f09c31f6d35b8a2a
