### ISSUE TITLE
Make impossible for a non-member to sign someone else

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/cutecoin#55]
I could signed people with my account which is not a member.
It wasn't accepted by nodes.

**Comment by M5oul** [comment]
![signed](https://cloud.githubusercontent.com/assets/4758871/6119692/7386bc4a-b0cc-11e4-92b1-1641a7229cec.png)

**Comment by Insoleet** [comment]
Fixed in https://github.com/ucoin-io/cutecoin/commit/7f472be06dd6eba8fdb52a2caf1b0a32cc8d9d1f
