### ISSUE TITLE
Display issue on referential choise

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/cutecoin#57]
Referencial choises: `Units`, `UD`, `Relative Z-sum` and `Quantitative Z-sum` are displayed many times in my case. Almost twice my screen size. I can't take a screenshot :(

**Comment by Insoleet** [comment]
Oh this is a weird bug.
Do you have any log or use case so I can try to reproduce them ?

**Comment by M5oul** [comment]
It happends when I reopen an account on the same CuteCoin session.

**Comment by Insoleet** [comment]
https://github.com/ucoin-io/cutecoin/commit/12e835b70d3b16a5061705c1c0fa5977e349ddea
