### ISSUE TITLE
Cross to close windows not displayed under GNOME 3.1X

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/cutecoin#58]
![cross](https://cloud.githubusercontent.com/assets/4758871/6120021/79fdb25a-b0d0-11e4-9c3e-868b84a0de7a.png)

**Comment by Insoleet** [comment]
It looks like a Gnome "feature" : 
https://stackoverflow.com/questions/8691025/qt-qdialog-and-gnome-3-how-to-display-the-close-button-title-bar-and-make-it-mo

**Comment by M5oul** [comment]
I could not found anything in gconf-editor: Desktop > Gnome > Shell > Windows:

![capture du 2015-02-14 15 12 32](https://cloud.githubusercontent.com/assets/4758871/6199851/64a62312-b45c-11e4-8cca-7b37ee492478.png)

May be this could help:
http://blog.pitonyak.org/node/18

**Comment by Insoleet** [comment]
Yes I saw this hack, but its a very dirty one...

It's not a bug, it's a gnome 3 feature. :)
