### ISSUE TITLE
Warning at first step accounting with a password ending with a `\n`

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/cutecoin#59]
I could pass the first step with a password ending with `\n`:
![accounting](https://cloud.githubusercontent.com/assets/4758871/6120106/c74e291c-b0d1-11e4-9c14-a285f97aca7e.png)
And, I get an error at next step:
![passwd](https://cloud.githubusercontent.com/assets/4758871/6120111/d6627b10-b0d1-11e4-91ab-415e7fff7487.png)
A warning should prevent at the first step that the password shouldn't ends with a `\n`.

**Comment by Insoleet** [comment]
https://github.com/ucoin-io/cutecoin/commit/22cab049884634be1a15774f1ce3309dcce84c8a
