### ISSUE TITLE
0.8.0 informations tab

### ISSUE THREAD

**Issue by galuel** [ucoin-io/cutecoin#62]
tab is generally correct but some information are wrong : 

General : 
- Actual % growth c is wrong (0,04% instead of near 10%, check calculation) + write " / day"

Money : 
- "Growth parameter c" should be "Fundamental growth parameter c", since growth is not always "c". + missing time unit : / day
- Missing "definition of day" = "when exactly the Dividend is added to the blockchain ?! 23h59 ? 12h47 ? Number of blocks ? Average network time ? What is the rule ?
- Initial Universal Dividend + "UD(0)" in mb

Wot : should be placed in another tab, WoT rules are independant part of money rules. I suppose in "information tab" it should be interesting to have a "money tab" and a "WoT tab" to isolate them.

Rules : "money rules"
- "Fundamental growth parameter c"
- UD formula : UD(t+1) and not UDt+1, the same with UD(t), M(t+1) N(t+1) place "[" or "{" when you have more levels like : Max {UD(t);c*M(t)/N(t+1)}
- UD computed : I see MAX {100 mb ...) which is not correct, since it should be UD(t) = 124 mb, it is a mistake replaced by UD(0) instead of UD(t) + N(t+1) instead of real value N(t) = 16

=> Replace formula by UD(t) = MAX {UD(t-1);c*M(t)/N(t-1)} and give information of N(t-1) as well as N(t); and also UD(t-1) as well as UD(t), and M(t-1) as well as M(t) we need 2 steps of time to check validity. I propose you put "General money information (t)" and "General money information (t-1)" as separated information blocks at the top (you could do that in 2 horizontal blocks, with "t" at the left and "t-1" at the right).

**Comment by vtexier** [comment]
Money and Rules mistakes are fixed. Please check image below.
![cutecoin_infos](https://cloud.githubusercontent.com/assets/2174016/6175184/cf809ec4-b2f4-11e4-9151-12908a1ea877.png)

**Comment by galuel** [comment]
Yes it seems ok to me. I think it could be even better to have 2 tabs in informations tab (like we have 2 tabs into community tab), one for money informations and another for WoT.

**Comment by vtexier** [comment]
Fixed in 8db386e3ab4ea665c4804858fc8dd12f2218b92c
