### ISSUE TITLE
Transfer error : "Argument of type ValueError is not iterable", but the transfer exists in the transaction list

### ISSUE THREAD

**Issue by blavenie** [ucoin-io/cutecoin#64]
I tried to apply a transfer, with the following comment : "cool cutecoin, isn't it ?"
but cutecoin display an error message : "Argument of type ValueError is not iterable"
So i remove the comma in comments, and the transfer was accepted.

In the transaction list, i could see both transfer : the first (bad) one and good one.
I should not see the bad transfer, isn't it ? ;)

Thks guys for all your work !!

**Comment by blavenie** [comment]
Idem pour les caractères non ascii (le message est clair, mais la transaction est tout de même dans la liste)

**Comment by Insoleet** [comment]
Fixed in https://github.com/ucoin-io/cutecoin/commit/b5b4dae43f4dd30fb69261915a356783b0a4bbab
