### ISSUE TITLE
Password minimal length

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/cutecoin#65]
I could pass the following step with a 2 char length password.
![accounting](https://cloud.githubusercontent.com/assets/4758871/6129187/ad618f10-b13c-11e4-9e56-abe0abf64646.png)
I don't know if password minimal length is ever set in CuteCoin or in uCoin. But it should ask for a minimal 4 or 6 char password and refused shorter one.

**Comment by Insoleet** [comment]
Let's ask for at least 6 characters in next version.
https://github.com/ucoin-io/cutecoin/commit/8f35e30300865821a82e8ce3fbdd73ad61b6b95b
