### ISSUE TITLE
Transaction sort behavior

### ISSUE THREAD

**Issue by c-geek** [ucoin-io/cutecoin#67]
When I try to sort my transactions by payment/deposit, "blank" values still stand between sorted values.

I expected at least not to have those blank lines in between valued lines. At most, I would have seen blank rows at the bottom whichever is the sort (ASC or DESC).

Example:
![wrong_sort](https://cloud.githubusercontent.com/assets/969136/6133803/ca827f80-b15c-11e4-89ea-840e1489ff96.png)

**Comment by Insoleet** [comment]
https://github.com/ucoin-io/cutecoin/commit/5652bad7b2100613af09e3914a761e1abec77d95
