### ISSUE TITLE
Money units case

### ISSUE THREAD

**Issue by c-geek** [ucoin-io/cutecoin#68]
Almost everywhere in the app, it can be seen `mb` and `ud mb` in lower case. Wouldn't it be better to have it uppercased?

![unit_case](https://cloud.githubusercontent.com/assets/969136/6133877/6dea1d86-b15d-11e4-844b-4489468c21c6.png)

**Comment by Insoleet** [comment]
I'm not sure. I opened a topic on the forum to have more opinions.
http://forum.ucoin.io/t/cutecoin-0-8-released/169/8

**Comment by M5oul** [comment]
I'm agree with upercases.

**Comment by Insoleet** [comment]
Fixed https://github.com/ucoin-io/cutecoin/commit/1d5a1caf740fff6f90b75abcb330f8c0258b7cfd
