### ISSUE TITLE
Dates should be localized in english format

### ISSUE THREAD

**Issue by vtexier** [ucoin-io/cutecoin#72]
The software is in english for now. So dates should be as well.

**Comment by vtexier** [comment]
https://www.englishclub.com/vocabulary/time-date.htm

We are using the "D" format. In that format, british dates can be as French dates. But not american ones. What is our official english language : en_UK or en_US ?

**Comment by Insoleet** [comment]
We have no official language, the dates are displayed by Qt depending on OS language.

**Comment by Insoleet** [comment]
https://github.com/ucoin-io/cutecoin/commit/2929944206067c9c2b4a04a3f08abb8b851a4f9a
