### ISSUE TITLE
The Wot view implements too much core code

### ISSUE THREAD

**Issue by Insoleet** [ucoin-io/cutecoin#73]
I think the wot view implements too much core code.

Certifiers-of and certified-by could be moved to the Person class for example. This would help to create different wot view later without having to work on the core code each time.

**Comment by vtexier** [comment]
Yes, sure.
certified/certifiers are done.
I will refactor too : send_money, add_contact, etc...

**Comment by Insoleet** [comment]
send_money uses the wallet, not the person

What do you want to refactor in those methods ?

**Comment by vtexier** [comment]
They are in two places, community tab and wot tab , because I copy paste them. We need to have it once only. Respecting the DRY principle.

**Comment by Insoleet** [comment]
Ah yes I agree.

It could be done by connecting to core package classes. I think it is
related to the work that must be done about inheriting core package classes
from QObject.

2015-02-20 9:20 GMT+01:00 vtexier <notifications@github.com>:

**Comment by Insoleet** [comment]
https://github.com/ucoin-io/cutecoin/commit/8fc39c14ed92e2aa5a131d143e5e6438bc22ab82
