### ISSUE TITLE
Progress bar on startup?

### ISSUE THREAD

**Issue by c-geek** [ucoin-io/cutecoin#75]
When launching 0.8.1 for the first time, I had to wait approx. 20-25 seconds for cutecoin to be loaded and fully respond.

Could we have some kind of progress bar/loading message (with %) to see this waiting is absolutely normal?

**Comment by Insoleet** [comment]
https://github.com/ucoin-io/cutecoin/commit/350361683f89d32d6e61b410f445b3c6444c2289
