### ISSUE TITLE
Starting connecting to currency && network information

### ISSUE THREAD

**Issue by galuel** [ucoin-io/cutecoin#77]
About nitializing a new account and connecting it to the network. I suppose we should create an account in one tab (ID,...), and have another tab where we can write and read information about the network (URL, port, connected peers, other information...).

The same tab should be available at any time in "preferences", or elsewhere, to be able to see the network information, perhaps like it is in the webdemo : http://www.metab.ucoin.io/#/tech . I guess like something we have in Qbittorrent P2P interface : http://basunerat.se/wp-content/uploads/2013/04/qb111-300x232.png

**Comment by Insoleet** [comment]
https://github.com/ucoin-io/cutecoin/commit/16d64dda283c04985524abbd37ee27f03420f66a
