### ISSUE TITLE
Join date wrong

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/cutecoin#79]
There is an issue the join date value:
![join-date](https://cloud.githubusercontent.com/assets/4758871/6279350/8c6e89d2-b8a0-11e4-8b7a-819d99da8be1.png)
For instance, cgeek joined the community the same day as moul account.

**Comment by Insoleet** [comment]
This is last renew date. The label should be changed.

**Comment by Insoleet** [comment]
Forgot to work on the fix for 0.8.2, will be done in 0.9...

**Comment by Insoleet** [comment]
https://github.com/ucoin-io/cutecoin/commit/350361683f89d32d6e61b410f445b3c6444c2289
