### ISSUE TITLE
Add various hints in status bar for service improvement

### ISSUE THREAD

**Issue by toearc** [ucoin-io/cutecoin#82]
"Warning: Membership expiration in 0 days" could be replaced with some helpful hints for service-improvement at low prio

**Comment by Insoleet** [comment]
I don't have any idea for such hints.. Suggestions welcome !

**Comment by toearc** [comment]
"Membership is expired and must be renewed on demand" <- verb could be the
same as in the phrase on the corresponding button

2015-02-24 20:56 GMT+01:00 Insoleet <notifications@github.com>:
