### ISSUE TITLE
Could not sync over block #5416 on meta_brouzouf

### ISSUE THREAD

**Issue by c-geek** [ucoin-io/cutecoin#83]
I don't know why, but I can' sync over this block. Here is the content of my cache : http://pastebin.com/dX5JEjAr

**Comment by Insoleet** [comment]
What do you mean by "could not sync" ?

**Comment by c-geek** [comment]
I mean cutecoin tells me "Connected : Block 5416". But I've just clicked "Account > Configure" menu,  have removed meta_brouzouf community, selected my node again (metab.ucoin.io:9201) and I was connected to block 5540.

Probably a fork issue from existing node.

**Comment by Insoleet** [comment]
Ah yes, probably. 

In 0.9 I'll monitor the network in a tab. I'll use this to only request synced nodes.
