### ISSUE TITLE
Search form in the members table tab

### ISSUE THREAD

**Issue by vtexier** [ucoin-io/cutecoin#85]
We should have a search form in the members table tab.

Like the WoT tab, we should display only directly connected members (so table load faster), and search for the others with the form.

This way, we can add a menu "Show in members" in the WoT, to have additional informations about the member.

**Comment by Insoleet** [comment]
Tab will be renamed "Identities" so that we can also look for non-members.

**Comment by Insoleet** [comment]
https://github.com/ucoin-io/cutecoin/commit/a5c305bbae3f086dda81143b13942bce0fec4f4a
