### ISSUE TITLE
Ubuntu 14.04 installation problem

### ISSUE THREAD

**Issue by mhugo** [ucoin-io/cutecoin#86]
I'm trying to use cutecoin on ubuntu 14.04 without success ...

I've downloaded the "3.4" binary release for ubuntu. When I launch it, I get a weird dialog without any menu or particular buttons ... 
![cutecoin_exe](https://cloud.githubusercontent.com/assets/1618556/6442134/cf545100-c0ed-11e4-88a4-76fc770d8f03.jpg)

I then tried to launch it from the sources.
I first had to manage how to install cx_Freeze. It does not compile correctly on unbuntu 
https://bitbucket.org/anthony_tuininga/cx_freeze/issue/32/cant-compile-cx_freeze-in-ubuntu-1304
Then after "python3 setup.py build" I get : 
```
Traceback (most recent call last):
  File "setup.py", line 48, in <module>
    icon = None,
TypeError: __init__() got an unexpected keyword argument 'compress'
```

I then tried to bypass cx_Freeze. I copied main.py and added some directories in the sys.path and managed to get it launched ... but with the same blank screen : 
![cutecoin_src](https://cloud.githubusercontent.com/assets/1618556/6442182/36d800b0-c0ee-11e4-8d96-7526d9ae367e.jpg)

Am I missing something obvious ?

**Comment by Insoleet** [comment]
On Ubuntu, the menu is in the top bar.
You'll have to add an account from there to not have a blank screen.

But i'm thinking about it now, having a homescreen could be a nice feature.

**Comment by mhugo** [comment]
I use ubuntu with an old gnome2 menu (no unity). So that menus are displayed in their windo, rather than in the top bar. 
But thanks to your feedback, I will have a look at this ubuntu menu issue

**Comment by mhugo** [comment]
Ok, it was actually easy : 
```
apt-get remove appmenu-qt5
```
