### ISSUE TITLE
Need for alerts about membership & certifications expiration

### ISSUE THREAD

**Issue by c-geek** [ucoin-io/cutecoin#9]
It would be very useful to be noticed about these events of expiration, since this can  kick us from the WoT.

Membership has to be renewed every X days (written in the currency parameters), and certifications simply expire (delay is also in currency parameters).

For certifications, you can use **certifiers-of** method.
For membership, I know I should provide a new method to retrieve the information, since it does not exist yet. I will do it ASAP!

**Comment by Insoleet** [comment]
https://github.com/ucoin-io/cutecoin/commit/5490f3348e434e63d14304b3067eba798022a9f4
