### ISSUE TITLE
Cannot use salt/password with few characters count

### ISSUE THREAD

**Issue by c-geek** [ucoin-io/cutecoin#90]
For example, I cannot have abc/def as salt/password. Cutecoin *warns* me that I should have longer salt/password, but also disables the *Next* button.

It should either allow for using short salt/password, or say "forbidden" rather than "warning".

I prefer the 1st option.

**Comment by Insoleet** [comment]
Well with @vtexier , we thought that we should forbid too short combinations. 

Maybe we should change the text. But the as the account/pasword is can't be changed back, I don't think we should let users set a too short one.

**Comment by c-geek** [comment]
Ok, np.
