### ISSUE TITLE
Cannot connect to a node whose port is > 9999

### ISSUE THREAD

**Issue by c-geek** [ucoin-io/cutecoin#92]
I need to connect to some node on port `60536`, but the port input text only allows me 4 characters length.

**Comment by Insoleet** [comment]
Actually the limit was on 25000. Why ? Dunno ^^

Will be fixed in next major release since its coming very soon.

**Comment by c-geek** [comment]
Okay :-)

The limit is actually 65536 with IP (2^16). This precise limit would be great!
