### ISSUE TITLE
Numbers representation with spaces 

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/cutecoin#97]
It could be better to display numbers with spaces to facilitate reading.
For instance: M = 2848111 -> 2 848 111

**Comment by vtexier** [comment]
Good idea. It will be done with the locale implementation http://doc.qt.io/qt-5/qlocale.html.
Numbers will be displayed according to language.

**Comment by vtexier** [comment]
Currency amounts displayed with commas for english (5,000,000.00 MB) and spaces for french (5 000 000,00 MB).
Done in 1600d26e71359c8a12893f30b35dc3bae36129c4
