### ISSUE TITLE
Change size of column in transaction tab

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/cutecoin#99]
It is not possible to change size of column in transaction tab although in wallets and Network it is possible.

**Comment by vtexier** [comment]
uid/pubkey column header and contents were truncated and column not resizable.
I have solved the truncate problem by using the "resizeToContents".
Now, the column is resizable, but the header and contents are truncated again...
I think we don't need to resize columns if contents are not truncated.

**Comment by Insoleet** [comment]
So case is closed ?

**Comment by vtexier** [comment]
No. Resize to contents has been removed. So header text and u ids are truncated...
I think we should put it back to avoid truncating contents. But then,  column will not be resizable.

**Comment by Insoleet** [comment]
Can't we set it resizable and not truncated by default?

**Comment by Insoleet** [comment]
Please check out the last commit. I think it's a pretty fix to the described problem.

**Comment by vtexier** [comment]
Checked. Working great !
